import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print('___________________________________________')
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

print('___________________________________________')
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)